### ISSUE TITLE
Support for multiple templates

### ISSUE THREAD

**Issue by jeroenrinzema** [NYTimes/drone-gke#104]
I would like to reuse parts of my YAML configurations across different pipeline steps for different cluster environments ex.: staging, testing and production. But for example not ingress configurations.

Currently is this plausible by defining different YAML files for every environment and assigning the different files to the `template` parameter. But this creates a lot of code duplication and makes it harder to preform changes to the Kubernetes configurations since the whole YAML configuration has to get duplicated.

Support for multiple template/secret files could allow configurations to be reused. Multiple templates are optional and could be defined by assigning an array to the `template` parameter instead of a string. This makes the feature both forward and backward compatible:

```yaml
# Multiple template files:
template:
  - .kube.yml
  - .kube-ingress-test.yml

# Single template file:
template: .kube.yml
```

Besides the template parameter could the `secret_template` parameter also get support for multiple templates to keep consistency across the plugin configuration.
