### ISSUE TITLE
Token not being found

### ISSUE THREAD

**Issue by ConradKurth** [nytimes/drone-gke#119]
Hello

I am having trouble with the token in drone. My yaml is as follows

```yaml
image: nytimes/drone-gke:k8s-1.11
expand_env_vars: true
token: >
   $$GOOGLE_CREDS
```

It is still saying that token is not set, but that env var is set as as secret
```

Drone GKE Plugin built from 88679fcb947304ea35dde46ed60db3ce315c4a9d
--
 Missing required param: token
```

From the docs you say you need to put it in secrets? And then I see blogs about putting it in the higher level where I have done. Can this be cleared up for me? I can run it locally by setting the env var to token, so not sure why the plugin is not working

**Comment by oliver-nyt** [comment]
Which drone version are you running?

For drone 1.x you need to put the `token` key under `settings`, e.g. like this:

```
image: nytimes/drone-gke:k8s-1.11
settings
  token: >
     $$GOOGLE_CREDS
```

**Comment by ConradKurth** [comment]
Thanks for getting back to me @oliver-nyt 

Hmmm. I am running 1.3 version of drone.
I have updated my yaml to be..

```yaml
- name: deploy  
  image: nytimes/drone-gke:k8s-1.11
  settings:
    token: >
      $$GOOGLE_CREDS
    wait_seconds: 60
    expand_env_vars: true
```

I am still getting 
```
Drone GKE Plugin built from 88679fcb947304ea35dde46ed60db3ce315c4a9d
| Missing required param: token
```
I have added the secret via the UI. Maybe the env variable is not being set? Not sure what else is going on

**Comment by oliver-nyt** [comment]
My bad, I forgot that in drone 1.x the secrets are handled a little differently, you have to use `from_secret`.
Try this:

```
- name: deploy  
  image: nytimes/drone-gke:k8s-1.11
  settings:
    token:
      from_secret: google_creds
    wait_seconds: 60
    expand_env_vars: true
```

**Comment by ConradKurth** [comment]
Well unfortunately that does not work either

```yaml
- name: deploy  
  image: nytimes/drone-gke:k8s-1.11
  settings:
    token:
      from_secret: GOOGLE_CREDS
```

There is a place in the docs that says you need to set the token in the secrets part? With the target being token? Is that applicable at all?

**Comment by oliver-nyt** [comment]
You can try it by moving it into the `environment` section like this:

```
- name: deploy  
  image: nytimes/drone-gke:k8s-1.11
  environment:
    TOKEN:
      from_secret: GOOGLE_CREDS
```
